apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  labels:
  {{ include "labels.major" . | nindent 4 }}
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "6"
  ui_properties_file_name: "user-interface.properties"