apiVersion: v1
kind: Pod
metadata:
  name: my-first-app-1
  labels:
    {{ include "labels.major" . | nindent 4 }}
spec:
  containers:
    - name: nginx
      image: {{  default "nginx" .Values.image.name  }}
      {{/*
      
      env:
      {{- range $key, $value := $.Values.env }}
      - name: {{ $key }}
        value: {{ $value }}
      {{- end }}
      
      */}}
      {{- if .Values.probes -}}
      {{ toYaml .Values.probes | nindent 6 }}
      {{- end -}} 
      