apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
{{ include "labels.major" . | nindent 4 }}
spec:
  ports:
  - name: front-end
    port: 80
    targetPort: 8080 
  selector:
    app: my-app
    version: v1.0.0